import java.awt.Dimension;
import java.util.ArrayList;

import javax.swing.*;

public class BloonsRunner {
	
	public static final int WIDTH = 1000, HEIGHT = 550, PATH_WIDTH = 50;
	
	public static String phase = "pregame";
	public static String gamePhase = "pregame";
	public static int round = 0;
	public static Bloon[] currentBloons;
	public static int lastRound = 0;
	public static int health = 50;
	public static int money = 0;
	public static GameMap map;
	public static Bloon[][] maps = {
		// Round 1 -- 20 Red
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red")},
		// Round 2 -- 30 Red
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red")},
		// Round 3 -- 20 Red, 5 Blue
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue")},
		// Round 4 -- 30 Red, 15 Blue
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue")},
		// Round 5 -- 5 Red, 25 Blue
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue")},
		// Round 6 -- 15 Red, 15 Blue, 4 Green
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green")},
		// Round 7 -- 20 Red, 25 Blue, 5 Green
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green")},
		// Round 8 -- 10 Red, 20 Blue, 14 Green
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green")},
		// Round 9 -- 30 Green
		{new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green")},
		// Round 10 -- 102 Blue
		{new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue")},
		// Round 11 -- 10 Red, 10 Blue, 12 Green, 2 Yellow
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("yellow"), new Bloon("yellow")},
		// Round 12 -- 15 Blue, 10 Green, 5 Yellow
		{new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow")},
		// Round 13 -- 100 Red, 23 Green, 4 Yellow
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"),  new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow")},
		// Round 14 -- 50 Red, 15 Blue, 10 Green, 9 Yellow
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"),  new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("blue"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow")},
		// Round 15 -- 20 Red, 12 Green, 5 Yellow, 3 Pink
		{new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("red"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("green"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("yellow"), new Bloon("pink"), new Bloon("pink"), new Bloon("pink")}
	};
	
	// Hardcode bloons
	
	
	public static void main(String[] args) {
		JFrame f = new JFrame("Bloons Tower Defense");
		f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		BloonsWindow w = new BloonsWindow();
		f.add(w);
		f.setSize(WIDTH, HEIGHT);
		f.setResizable(false);
		f.setLocationRelativeTo(null);
		f.setVisible(true);
	}

}
